class test_data_inputs:
    valid_template_name = "AUT_Valid_Template"
    valid_template_description = "Automation test template description"
    valid_template_file = "template/Updated Audio template.zip"
    text_template_file = "template/Updated text template.zip"
    Invalid_template_name = "AUT_Invalid_Template"
    Invalid_template_description = "Automation test template description"
    Invalid_template_file = ["invalid/Sample-BAT-File-calculator.bat"]
    duplicate_template_name = "AUT_Template_Duplicate"
    special_char_template_name = "AUT_@$%%$_Hello"
    capital_duplicate_template_name = "AUT_TEMPLATE_DUPLICATE"
    search_template_name = "AUT_Search_Temp"
    non_existing_template_name = "Checking_Template_Not_There"
    delete_template_names = ["AUT_Delete_Template_1", "AUT_Delete_Template_2", "AUT_Delete_Template_3", "AUT_Delete_Template_4"]
    prevent_template_dataset_name = "AUT_Prevent_Temp_Dataset"
    prevent_template_name = "AUT_Delete_Template"
    prevent_template_workflow_name = "AUT_Prevent_Temp_WorkFlow"
    prevent_template_project_name = "AUT_Prevent_Temp_Project"
    prevent_template_node_list = ["Start", "Annotate", "Review", "Complete"]
    Audio_Files = ["audio/audio 2.flac"]
    Template_files_upload = ["template/Updated Audio template.zip"]
    bulk_prevent_template_1 = "AUT_Bulk_Template_1"
    bulk_prevent_template_2 = "AUT_Bulk_Template_2"
    bulk_prevent_workflow_name = "AUT_Bulk_Prevent_WorkFlow"
    bulk_prevent_node_list = ["Start", "Annotate", "Review", "Annotate", "Review", "Complete"]
    invalid_mixed_zip_file = "template/Mixed Files.zip"
    invalid_zip_template_name = "AUT_Invalid_Zip_Template"
    template_name_50_chars = "AUT_Boundary_Template_Name_50_Characters_Length_Ex"
    template_desc_2000_chars = "Description_" + ("A" * 1988)
    update_template_name = "AUT_Update_Template"
    updated_template_file = "template/Updated text template.zip"
    unlinked_delete_template_name = "AUT_Unlinked_Delete_Template"
    bulk_linked_dataset_name = "AUT_Bulk_Linked_Dataset"
    bulk_linked_template_name = "AUT_Bulk_Linked_Template"
    bulk_unlinked_template_name = "AUT_Bulk_Unlinked_Template"
    bulk_linked_workflow_name = "AUT_Bulk_Linked_Workflow"
    bulk_linked_project_name = "AUT_Bulk_Linked_Project"
    pagination_template_name = "AUT_Pagination_Template"
    template_50_chars_temp_name = "AUT_Template_50_Chars_Template"+ ("A"*50)
    workflow_50_chars_temp_name = "AUT_Workflow_50_Chars_Template"+ ("A"*50)
