name: Playwright Automation Tests

on:
  workflow_dispatch:
    inputs:

      test_paths:
        description: "Test folders to execute (comma separated)"
        required: true
        default: "tests/objectwaysSanity"
        type: string

      qa_url:
        description: "QA URL"
        required: true
        default: "https://fmn-qa.tensoract.com"
        type: string

jobs:

  playwright-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Create Environment File
        run: |
          echo "QA_url_2=${{ inputs.qa_url }}" >> .env
          echo "company_Username=${{ secrets.COMPANY_USERNAME }}" >> .env
          echo "company_Password=${{ secrets.COMPANY_PASSWORD }}" >> .env

      - name: Run Playwright Tests
        shell: bash
        run: |
          IFS=',' read -ra TEST_PATHS <<< "${{ inputs.test_paths }}"

          pytest "${TEST_PATHS[@]}"